
version: "3.8"


volumes:
  posgres_vol:

networks:
  postgres_net:
    driver: bridge

services:
  postgres:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    networks:
      - postgres_net
    volumes:
      - posgres_vol:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4:6.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 8083:80
    networks:
      - postgres_net
    depends_on:
      - postgres
