
version: "3.8"

volumes:
  mongo_vol:

networks:
  mongo_net:
    driver: bridge

services:
  mongodb:
    image: mongo:4.4.3
     # Attention! Opens port 27017
    ports:
      - 27017:27017
    networks:
      - mongo_net
    volumes:
      - mongo_vol:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
     # Attention! Opens port 8081
    ports:
      - 8081:8081
    networks:
      - mongo_net
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/admin