
version: "3.8"

volumes:
  maria_data:

networks:
  maria_net:
    driver: bridge

services:
  mariadb:
    image: mariadb:10.4
    restart: always
    # ports:
    #   - 3306:3306
    networks:
      - maria_net
    volumes:
      - maria_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin:5.1.1
     # Attention! Opens port 8082
    ports:
      - 8082:80
    networks:
      - maria_net
    depends_on:
      - mariadb
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
