version: "3.8"

volumes:
  redis_data:

networks:
  redis_net:
    driver: bridge

services:
  redis:
    image: redis:6.2.6
    command:
      redis-server --appendonly yes
      # Attention! Opens port 6379
    ports:
      - 6379:6379
    networks:
      - redis_net
    volumes:
      - redis_data:/data
    environment:
      - REDIS_REPLICATION_MODE=master

  redis-comander:
    image:
      rediscommander/redis-commander:latest
      # Attention! Opens port 8084
    ports:
      - 8084:8081
    networks:
      - redis_net
    depends_on:
      - redis
    environment:
        - REDIS_HOSTS=local:redis:6379